# Numpy

In [3]:
from numpy import random
import numpy as np

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [4]:
arr = random.uniform(0,20,28)

arr = np.reshape(arr, [7, 4])
print('Сгенерированный массив:\n', arr)
arr = (arr - arr.min()) / (arr.max() - arr.min())
print('\nНормализованный массив:\n', arr)

Сгенерированный массив:
 [[14.38911512  1.4722475   6.8292833  16.08681646]
 [14.09403386  1.49955676 17.93241288 16.72182214]
 [17.26295701  9.10224768 16.12226182  1.91673546]
 [16.15806986  4.95351713  9.87384741  9.04450535]
 [13.98118572  1.30235614  3.74519553  9.74533649]
 [19.30986738  5.10345987  7.21383831  4.15363223]
 [ 4.72548995 14.99555019  6.25513563 14.97448336]]

Нормализованный массив:
 [[0.7267389  0.00943447 0.30692343 0.8210163 ]
 [0.71035234 0.01095102 0.92350667 0.85627968]
 [0.88633019 0.43314656 0.82298467 0.03411795]
 [0.82497317 0.20275767 0.47599533 0.42993999]
 [0.70408561 0.         0.13565669 0.46885881]
 [1.         0.21108435 0.32827869 0.15833815]
 [0.19009478 0.76041569 0.27503964 0.7592458 ]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [5]:
arr2 = random.randint(0, 10, [8, 10])

print('Сгенерированный массив:\n', arr2)
minind = arr2.sum(axis=1).argmin()
print('\nИндекс строки с минимальной суммой элементов:', minind, '\nСтрока с минимальной суммой:', arr2[minind])  

Сгенерированный массив:
 [[8 1 3 1 6 6 5 0 5 7]
 [4 1 6 3 8 8 7 7 9 6]
 [5 9 7 9 6 6 6 2 5 6]
 [4 9 9 5 5 3 1 8 0 6]
 [0 6 8 0 8 5 5 7 9 1]
 [2 9 5 7 9 4 9 1 0 4]
 [7 2 1 1 7 8 7 9 5 0]
 [4 3 9 5 6 4 3 6 3 9]]

Индекс строки с минимальной суммой элементов: 0 
Строка с минимальной суммой: [8 1 3 1 6 6 5 0 5 7]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [6]:
size_v = random.randint(3, 6)
v1 = random.randint(0, 10, size_v)
v2 = random.randint(10, 20, size_v)

print('Вектор v1:\n', v1, '\nВектор v2:\n', v2)
dist = np.linalg.norm(v1-v2)

print('\nЕвклидово расстояние:\n',dist)

Вектор v1:
 [1 9 1] 
Вектор v2:
 [18 19 16]

Евклидово расстояние:
 24.779023386727733


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [7]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
Cneg = -1 * C
invA = np.linalg.inv(A)
# np.linalg.inv(A) * (-1 * C) * np.linalg.inv(B)
# X = invA * -C * invB
np.matmul(np.matmul(invA, Cneg), np.linalg.inv(B))

array([[ 1.00000000e+00,  5.32907052e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [8]:
data = np.genfromtxt('data/minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skip_header=True )#, names=True).astype(np.int32)
data[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [9]:
print('Средние значения:\n', data.mean(axis=0)[1:],'\nМаксимумы:\n', data.max(axis=0)[1:], '\nМинимумы:\n', data.min(axis=0)[1:])

Средние значения:
 [2.16010017e+04 9.05528000e+00] 
Максимумы:
 [2147483647         39] 
Минимумы:
 [0 1]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [10]:
#q75 = np.quantile(data[:, 1], 0.75)
# np.clip(data, 0, q75)
q75 = np.quantile(data[:, 1], 0.75)
np.clip(data[:, 1], 0, q75)

array([60., 25., 10., ..., 65.,  5., 65.])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [11]:
zer = np.where( data[:, 1] == 0)
print('Количество рецептов с нулевой продолжительностью:\n', len(zer[0]))
data[data[:, 1] == 0] = 1
np.where( data[:, 1] == 0)

Количество рецептов с нулевой продолжительностью:
 479


(array([], dtype=int64),)

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [12]:
len(np.unique(data))

100076

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [13]:
uni_ingr = np.unique(data[:, 2])
print('Уникальные кол-ва ингридиентов:\n', uni_ingr, '\nВсего:\n', len(uni_ingr))

Уникальные кол-ва ингридиентов:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39] 
Всего:
 37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [14]:
data[np.where( data[:, 1] > 5)]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [287943,     85,     15],
       [498432,     65,     15],
       [ 81993,    140,     14]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [15]:
ingrInMin = data[:, 1]/data[:, 2]
print('Игнредиентов на минуту для каждого рецепта:\n', ingrInMin, '\nМаксимум:\n', np.max(ingrInMin))

Игнредиентов на минуту для каждого рецепта:
 [ 3.75        3.57142857  1.66666667 ...  4.33333333  1.25
 10.        ] 
Максимум:
 268435455.875


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [16]:
top100min = data[data[:, 1].argsort()][::-1][:100]
print('Топ-100 по времени:\n', top100min, '\nСреднее кол-во ингредиентов:\n', np.average(top100min[:, 2]))

Топ-100 по времени:
 [[    261647 2147483647          8]
 [    216215     259260          7]
 [    425681     259205          2]
 [     98912     216015          4]
 [     70551     201610          7]
 [    236340     146880          5]
 [    242032     132495          3]
 [    184528     129620          3]
 [    236274     129615          5]
 [    236281     129615          5]
 [     13264     115230          4]
 [    105417      86405          2]
 [     41403      86400          4]
 [     34175      86400          3]
 [    142936      86400          9]
 [     93063      86400          2]
 [     42247      69120          2]
 [    255611      64815          3]
 [    140344      60555          3]
 [    101082      60540          7]
 [     46288      50405          5]
 [    246196      44655          4]
 [     30845      44645          3]
 [    344480      43380         22]
 [    102098      43380          4]
 [    254782      43250         15]
 [    209590      43230          8]
 [    2

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [17]:
data[np.random.choice(data.shape[0], 10, replace=False)]

array([[ 26957,     20,      5],
       [ 44891,     60,      7],
       [ 15990,     25,      4],
       [349612,   1445,      2],
       [ 52936,     75,     13],
       [259927,     20,     11],
       [205882,     35,     11],
       [180705,     45,      7],
       [380015,     80,     10],
       [455750,     10,      4]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [18]:
# len(data) / data[data[:, 2] < np.average(data[:, 2])].sum() * 100
low_ingrd = data[data[:, 2] < np.average(data[:, 2])]
# np.array(low_ingrd).size()

low_ingrd[:, 0].shape[0] / data[:, 0].shape[0]  * 100

58.989000000000004

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [19]:
mask_prime = np.where((data[:, 1] < 21) & (data[:, 2] < 6), 1, 0)
data_prime = np.c_[data, mask_prime]
data_prime

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [20]:
len(mask_prime[mask_prime == 1 ]) / data[:, 0].shape[0]  * 100

9.943

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [53]:
def conditions(x):
    if   x <= 10:   return "быстрый"
    elif x <  20:   return "стандарт"
    else:           return "долгий"

func         = np.vectorize(conditions)
recipe_class = func(data[:, 1])
                        #class         #time       #n_ingredients
data_grouped = np.stack((recipe_class, data[:, 1], data[:, 2]), axis=1)
data_grouped

array([['долгий', '60', '16'],
       ['долгий', '25', '7'],
       ['быстрый', '10', '6'],
       ...,
       ['долгий', '65', '15'],
       ['быстрый', '5', '4'],
       ['долгий', '140', '14']], dtype='<U11')