# Numpy

In [ ]:
from numpy import random
import numpy as np

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [6]:
arr = random.uniform(0,20,28)

arr = np.reshape(arr, [7, 4])
print('Сгенерированный массив:\n', arr)
arr = (arr - arr.min()) / (arr.max() - arr.min())
print('\nНормализованный массив:\n', arr)

Сгенерированный массив:
 [[ 8.8972361  14.23896785  6.4457853  19.33596122]
 [16.02027315  8.06902601  9.30117316 18.45427246]
 [ 6.52099695  2.52920944 14.47242899 12.56451045]
 [ 0.86958649 17.41152394  8.12265175  6.95454674]
 [10.2435136   3.34386986  8.47796637 14.73540791]
 [14.58310929  7.42851155 13.21750736 10.38347235]
 [15.12341829 19.87369416 14.78534936 18.17771138]]

Нормализованный массив:
 [[0.42241655 0.70349956 0.29342071 0.97170438]
 [0.7972322  0.37883597 0.4436718  0.92530974]
 [0.29737836 0.0873297  0.71578433 0.61538927]
 [0.         0.8704401  0.38165777 0.32019184]
 [0.49325795 0.13019729 0.40035449 0.72962234]
 [0.72160835 0.34513197 0.6497501  0.5006226 ]
 [0.75003952 1.         0.73225026 0.91075704]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [7]:
arr2 = random.randint(0, 10, [8, 10])

print('Сгенерированный массив:\n', arr2)
minind = arr2.sum(axis=1).argmin()
print('\nИндекс строки с минимальной суммой элементов:', minind, '\nСтрока с минимальной суммой:', arr2[minind])  

Сгенерированный массив:
 [[1 8 1 4 2 0 3 6 1 1]
 [7 8 7 4 0 1 5 1 5 8]
 [9 3 4 5 0 7 8 9 3 8]
 [8 9 3 0 9 5 2 2 8 6]
 [8 5 3 4 4 5 0 2 3 8]
 [2 3 8 4 1 7 2 9 2 1]
 [5 5 2 1 7 8 2 6 2 8]
 [4 9 1 0 1 5 3 8 7 4]]

Индекс строки с минимальной суммой элементов: 0 
Строка с минимальной суммой: [1 8 1 4 2 0 3 6 1 1]


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [8]:
size_v = random.randint(3, 6)
v1 = random.randint(0, 10, size_v)
v2 = random.randint(10, 20, size_v)

print('Вектор v1:\n', v1, '\nВектор v2:\n', v2)
dist = np.linalg.norm(v1-v2)

print('\nЕвклидово расстояние:\n',dist)

Вектор v1:
 [9 3 1 3] 
Вектор v2:
 [15 18 10 14]

Евклидово расстояние:
 21.517434791350013


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [9]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
Cneg = -1 * C
invA = np.linalg.inv(A)
# np.linalg.inv(A) * (-1 * C) * np.linalg.inv(B)
# X = invA * -C * invB
np.matmul(np.matmul(invA, Cneg), np.linalg.inv(B))

array([[ 1.00000000e+00,  5.32907052e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [50]:
data = np.genfromtxt('data/minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skip_header=True )#, names=True).astype(np.int32)
data[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [54]:
print('Средние значения:\n', data.mean(axis=0)[1:],'\nМаксимумы:\n', data.max(axis=0)[1:], '\nМинимумы:\n', data.min(axis=0)[1:])

Средние значения:
 [2.16010017e+04 9.05528000e+00] 
Максимумы:
 [2147483647         39] 
Минимумы:
 [0 1]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [68]:
#q75 = np.quantile(data[:, 1], 0.75)
# np.clip(data, 0, q75)
q75 = np.quantile(data[:, 1], 0.75)
np.clip(data[:, 1], 0, q75)

array([60., 25., 10., ..., 65.,  5., 65.])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [88]:
zer = np.where( data[:, 1] == 0)
print('Количество рецептов с нулевой продолжительностью:\n', len(zer[0]))
data[data[:, 1] == 0] = 1
np.where( data[:, 1] == 0)

Количество рецептов с нулевой продолжительностью:
 479


(array([], dtype=int64),)

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [92]:
len(np.unique(data))

100076

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [94]:
uni_ingr = np.unique(data[:, 2])
print('Уникальные кол-ва ингридиентов:\n', uni_ingr, '\nВсего:\n', len(uni_ingr))

Уникальные кол-ва ингридиентов:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39] 
Всего:
 37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [96]:
data[np.where( data[:, 1] > 5)]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [287943,     85,     15],
       [498432,     65,     15],
       [ 81993,    140,     14]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [102]:
ingrInMin = data[:, 1]/data[:, 2]
print('Игнредиентов на минуту для каждого рецепта:\n', ingrInMin, '\nМаксимум:\n', np.max(ingrInMin))

Игнридиентов на минуту для каждого рецепта:
 [ 3.75        3.57142857  1.66666667 ...  4.33333333  1.25
 10.        ] 
Максимум:
 268435455.875


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [105]:
top100min = data[data[:, 1].argsort()][::-1][:100]
print('Топ-100 по времени:\n', top100min, '\nСреднее кол-во ингредиентов:\n', np.average(top100min[:, 2]))

Топ-100 по времени:
 [[    261647 2147483647          8]
 [    216215     259260          7]
 [    425681     259205          2]
 [     98912     216015          4]
 [     70551     201610          7]
 [    236340     146880          5]
 [    242032     132495          3]
 [    184528     129620          3]
 [    236274     129615          5]
 [    236281     129615          5]
 [     13264     115230          4]
 [    105417      86405          2]
 [     41403      86400          4]
 [     34175      86400          3]
 [    142936      86400          9]
 [     93063      86400          2]
 [     42247      69120          2]
 [    255611      64815          3]
 [    140344      60555          3]
 [    101082      60540          7]
 [     46288      50405          5]
 [    246196      44655          4]
 [     30845      44645          3]
 [    344480      43380         22]
 [    102098      43380          4]
 [    254782      43250         15]
 [    209590      43230          8]
 [    2

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [114]:
data[np.random.choice(data.shape[0], 10, replace=False)]

array([[183923,     25,      9],
       [ 57985,     90,     13],
       [136841,     45,      8],
       [404043,     20,      3],
       [ 56553,     55,      6],
       [297985,     70,     11],
       [189148,   2910,      6],
       [ 50934,     30,      7],
       [102796,    120,      7],
       [ 16375,     40,      8]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [141]:
# len(data) / data[data[:, 2] < np.average(data[:, 2])].sum() * 100
low_ingrd = data[data[:, 2] < np.average(data[:, 2])]
# np.array(low_ingrd).size()

low_ingrd[:, 0].shape[0] / data[:, 0].shape[0]  * 100

58.989000000000004

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [188]:
mask_prime = np.where((data[:, 1] < 21) & (data[:, 2] < 6), 1, 0)
data_prime = np.c_[data, mask_prime]
data_prime

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [196]:
len(mask_prime[mask_prime == 1 ]) / data[:, 0].shape[0]  * 100

9.943

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.